usr/share/backgrounds/ubuntukylin/artful.xml
usr/share/gnome-background-properties/artful-ubuntukylin-wallpapers.xml
usr/share/gnome-background-properties/artful-ubuntukylin-wallpapers.xml usr/share/ukui-background-properties
usr/share/backgrounds/seasons-autumn.jpg
usr/share/backgrounds/blue-city.jpg
usr/share/backgrounds/chinese-knot.jpg
usr/share/backgrounds/dazzle-light.jpg
usr/share/backgrounds/fantast.jpg
usr/share/backgrounds/purple-city.jpg
usr/share/backgrounds/starry-sky.jpg
