usr/share/backgrounds/ubuntukylin/disco.xml
usr/share/gnome-background-properties/disco-ubuntukylin-wallpapers.xml
usr/share/gnome-background-properties/disco-ubuntukylin-wallpapers.xml usr/share/ukui-background-properties
usr/share/backgrounds/twilight_in_the_north_of_xinjiang.jpg
usr/share/backgrounds/morning_dew.jpg
usr/share/backgrounds/dalian_tianmen_mountain_scenic_area.jpg
usr/share/backgrounds/sea_and_sky.jpg
usr/share/backgrounds/simple_light.jpg
usr/share/backgrounds/holiday_night.jpg
usr/share/backgrounds/cool_technology.jpg
usr/share/backgrounds/rest.jpg
usr/share/backgrounds/mountain_stream.jpg
usr/share/backgrounds/township_road.jpg
usr/share/backgrounds/star_bright.jpg
usr/share/backgrounds/clear_day_after_the_snow.jpg
usr/share/backgrounds/rapeseed_blossom.jpg
usr/share/backgrounds/tulip1904.jpg
usr/share/backgrounds/chinese_style.jpg
