usr/share/backgrounds/ubuntukylin/focal.xml
usr/share/gnome-background-properties/focal-ubuntukylin-wallpapers.xml
usr/share/gnome-background-properties/focal-ubuntukylin-wallpapers.xml usr/share/ukui-background-properties
usr/share/backgrounds/calla.png
usr/share/backgrounds/default.jpg
usr/share/backgrounds/dominate.jpg
usr/share/backgrounds/fristgeneration.jpg
usr/share/backgrounds/focal-ubuntukylin.png
usr/share/backgrounds/goldfish.png
usr/share/backgrounds/rhythm.jpg
usr/share/backgrounds/sight.jpg
usr/share/backgrounds/string.jpg
usr/share/backgrounds/the-mouse.jpg
usr/share/backgrounds/vapor.jpg
usr/share/backgrounds/view.jpg
