usr/share/backgrounds/ubuntukylin/focal.xml
usr/share/gnome-background-properties/focal-ubuntukylin-wallpapers.xml
usr/share/gnome-background-properties/focal-ubuntukylin-wallpapers.xml usr/share/ukui-background-properties
usr/share/backgrounds/calla.png
usr/share/backgrounds/city.png
usr/share/backgrounds/default.jpg
usr/share/backgrounds/desert.png
usr/share/backgrounds/firstgeneration.jpg
usr/share/backgrounds/fluent-color.png
usr/share/backgrounds/focal-ubuntukylin.png
usr/share/backgrounds/goldfish.png
usr/share/backgrounds/rhythm.jpg
usr/share/backgrounds/rollpaper.png
usr/share/backgrounds/string.jpg
usr/share/backgrounds/the-mouse.jpg
